//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMIWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Measurements = new HashSet<Measurement>();
        }
    
        public string SocialSecurityNumber { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<Measurement> Measurements { get; set; }
    }
}
