// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace BmiWeb_Test
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Enter_valid_weight_and_date - Use 'Enter_valid_weight_and_dateParams' to pass parameters into this method.
        /// </summary>
        public void Enter_valid_weight_and_date()
        {
            #region Variable Declarations
            HtmlEdit uISocialSecurityNumberEdit = this.UIBMIInternetExplorerWindow.UIBMIDocument1.UISocialSecurityNumberEdit;
            HtmlEdit uIBirthDateEdit = this.UIBMIInternetExplorerWindow.UIBMIDocument1.UIBirthDateEdit;
            HtmlComboBox uIGenderComboBox = this.UIBMIInternetExplorerWindow.UIBMIDocument1.UIGenderComboBox;
            #endregion

            // Type '123456' in 'socialSecurityNumber' text box
            uISocialSecurityNumberEdit.Text = this.Enter_valid_weight_and_dateParams.UISocialSecurityNumberEditText;

            // Type '{Tab}' in 'socialSecurityNumber' text box
            Keyboard.SendKeys(uISocialSecurityNumberEdit, this.Enter_valid_weight_and_dateParams.UISocialSecurityNumberEditSendKeys, ModifierKeys.None);

            // Type '02-05-1986' in 'birthDate' text box
            uIBirthDateEdit.Text = this.Enter_valid_weight_and_dateParams.UIBirthDateEditText;

            // Type '{Tab}' in 'birthDate' text box
            Keyboard.SendKeys(uIBirthDateEdit, this.Enter_valid_weight_and_dateParams.UIBirthDateEditSendKeys, ModifierKeys.None);

            // Select 'Male' in 'gender' combo box
            uIGenderComboBox.SelectedItem = this.Enter_valid_weight_and_dateParams.UIGenderComboBoxSelectedItem;
        }
        
        /// <summary>
        /// Enter_valid_weight_and_date_1 - Use 'Enter_valid_weight_and_date_1Params' to pass parameters into this method.
        /// </summary>
        public void Enter_valid_weight_and_date_1()
        {
            #region Variable Declarations
            HtmlEdit uILengthEdit = this.UIBMIInternetExplorerWindow.UIBMIDocument1.UILengthEdit;
            HtmlEdit uIWeightEdit = this.UIBMIInternetExplorerWindow.UIBMIDocument1.UIWeightEdit;
            HtmlEdit uIDateEdit = this.UIBMIInternetExplorerWindow.UIBMIDocument1.UIDateEdit;
            HtmlButton uIOKButton = this.UIBMIInternetExplorerWindow.UIBMIDocument1.UIOKButton;
            #endregion

            // Type '25' in 'length' text box
            uILengthEdit.Text = this.Enter_valid_weight_and_date_1Params.UILengthEditText;

            // Type '{Tab}' in 'length' text box
            Keyboard.SendKeys(uILengthEdit, this.Enter_valid_weight_and_date_1Params.UILengthEditSendKeys, ModifierKeys.None);

            // Type '75000' in 'weight' text box
            uIWeightEdit.Text = this.Enter_valid_weight_and_date_1Params.UIWeightEditText;

            // Type '{Tab}' in 'weight' text box
            Keyboard.SendKeys(uIWeightEdit, this.Enter_valid_weight_and_date_1Params.UIWeightEditSendKeys, ModifierKeys.None);

            // Type '02-05-2014' in 'date' text box
            uIDateEdit.Text = this.Enter_valid_weight_and_date_1Params.UIDateEditText;

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(22, 10));
        }
        
        /// <summary>
        /// OpenCreateNewPersonWindow
        /// </summary>
        public void OpenCreateNewPersonWindow()
        {
            #region Variable Declarations
            HtmlButton uINewButton = this.UIBMIInternetExplorerWindow.UIBMIDocument2.UINewButton;
            #endregion

            // Click 'New' button
            Mouse.Click(uINewButton, new Point(17, 7));
        }
        
        /// <summary>
        /// ValidateNewPersonSuccess - Use 'ValidateNewPersonSuccessExpectedValues' to pass parameters into this method.
        /// </summary>
        public void ValidateNewPersonSuccess()
        {
            #region Variable Declarations
            HtmlDiv uINewpersonwithsocialsPane = this.UIBMIInternetExplorerWindow.UIBMIDocument3.UIBodyPane.UINewpersonwithsocialsPane;
            #endregion

            // Verify that the 'InnerText' property of 'New person with social security number 1' pane equals 'New person with social security number 123456 added '
            Assert.AreEqual(this.ValidateNewPersonSuccessExpectedValues.UINewpersonwithsocialsPaneInnerText, uINewpersonwithsocialsPane.InnerText, "The new person is not added correctly");
        }
        
        #region Properties
        public virtual Enter_valid_weight_and_dateParams Enter_valid_weight_and_dateParams
        {
            get
            {
                if ((this.mEnter_valid_weight_and_dateParams == null))
                {
                    this.mEnter_valid_weight_and_dateParams = new Enter_valid_weight_and_dateParams();
                }
                return this.mEnter_valid_weight_and_dateParams;
            }
        }
        
        public virtual Enter_valid_weight_and_date_1Params Enter_valid_weight_and_date_1Params
        {
            get
            {
                if ((this.mEnter_valid_weight_and_date_1Params == null))
                {
                    this.mEnter_valid_weight_and_date_1Params = new Enter_valid_weight_and_date_1Params();
                }
                return this.mEnter_valid_weight_and_date_1Params;
            }
        }
        
        public virtual ValidateNewPersonSuccessExpectedValues ValidateNewPersonSuccessExpectedValues
        {
            get
            {
                if ((this.mValidateNewPersonSuccessExpectedValues == null))
                {
                    this.mValidateNewPersonSuccessExpectedValues = new ValidateNewPersonSuccessExpectedValues();
                }
                return this.mValidateNewPersonSuccessExpectedValues;
            }
        }
        
        public UIBMIInternetExplorerWindow UIBMIInternetExplorerWindow
        {
            get
            {
                if ((this.mUIBMIInternetExplorerWindow == null))
                {
                    this.mUIBMIInternetExplorerWindow = new UIBMIInternetExplorerWindow();
                }
                return this.mUIBMIInternetExplorerWindow;
            }
        }
        #endregion
        
        #region Fields
        private Enter_valid_weight_and_dateParams mEnter_valid_weight_and_dateParams;
        
        private Enter_valid_weight_and_date_1Params mEnter_valid_weight_and_date_1Params;
        
        private ValidateNewPersonSuccessExpectedValues mValidateNewPersonSuccessExpectedValues;
        
        private UIBMIInternetExplorerWindow mUIBMIInternetExplorerWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Enter_valid_weight_and_date'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class Enter_valid_weight_and_dateParams
    {
        
        #region Fields
        /// <summary>
        /// Type '123456' in 'socialSecurityNumber' text box
        /// </summary>
        public string UISocialSecurityNumberEditText = "123456";
        
        /// <summary>
        /// Type '{Tab}' in 'socialSecurityNumber' text box
        /// </summary>
        public string UISocialSecurityNumberEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '02-05-1986' in 'birthDate' text box
        /// </summary>
        public string UIBirthDateEditText = "02-05-1986";
        
        /// <summary>
        /// Type '{Tab}' in 'birthDate' text box
        /// </summary>
        public string UIBirthDateEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Select 'Male' in 'gender' combo box
        /// </summary>
        public string UIGenderComboBoxSelectedItem = "Male";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Enter_valid_weight_and_date_1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class Enter_valid_weight_and_date_1Params
    {
        
        #region Fields
        /// <summary>
        /// Type '25' in 'length' text box
        /// </summary>
        public string UILengthEditText = "25";
        
        /// <summary>
        /// Type '{Tab}' in 'length' text box
        /// </summary>
        public string UILengthEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '75000' in 'weight' text box
        /// </summary>
        public string UIWeightEditText = "75000";
        
        /// <summary>
        /// Type '{Tab}' in 'weight' text box
        /// </summary>
        public string UIWeightEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '02-05-2014' in 'date' text box
        /// </summary>
        public string UIDateEditText = "02-05-2014";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ValidateNewPersonSuccess'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class ValidateNewPersonSuccessExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'New person with social security number 1' pane equals 'New person with social security number 123456 added '
        /// </summary>
        public string UINewpersonwithsocialsPaneInnerText = "New person with social security number 123456 added ";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIBMIInternetExplorerWindow : BrowserWindow
    {
        
        public UIBMIInternetExplorerWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "BMI";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIBMIDocument UIBMIDocument
        {
            get
            {
                if ((this.mUIBMIDocument == null))
                {
                    this.mUIBMIDocument = new UIBMIDocument(this);
                }
                return this.mUIBMIDocument;
            }
        }
        
        public UIBMIDocument1 UIBMIDocument1
        {
            get
            {
                if ((this.mUIBMIDocument1 == null))
                {
                    this.mUIBMIDocument1 = new UIBMIDocument1(this);
                }
                return this.mUIBMIDocument1;
            }
        }
        
        public UIBMIDocument2 UIBMIDocument2
        {
            get
            {
                if ((this.mUIBMIDocument2 == null))
                {
                    this.mUIBMIDocument2 = new UIBMIDocument2(this);
                }
                return this.mUIBMIDocument2;
            }
        }
        
        public UIBMIDocument3 UIBMIDocument3
        {
            get
            {
                if ((this.mUIBMIDocument3 == null))
                {
                    this.mUIBMIDocument3 = new UIBMIDocument3(this);
                }
                return this.mUIBMIDocument3;
            }
        }
        #endregion
        
        #region Fields
        private UIBMIDocument mUIBMIDocument;
        
        private UIBMIDocument1 mUIBMIDocument1;
        
        private UIBMIDocument2 mUIBMIDocument2;
        
        private UIBMIDocument3 mUIBMIDocument3;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIBMIDocument : HtmlDocument
    {
        
        public UIBMIDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "BMI";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:15444/";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlButton UINewButton
        {
            get
            {
                if ((this.mUINewButton == null))
                {
                    this.mUINewButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUINewButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btnNewPerson";
                    this.mUINewButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUINewButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "New";
                    this.mUINewButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUINewButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUINewButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUINewButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"btnNewPerson\"";
                    this.mUINewButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUINewButton.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUINewButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUINewButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIBMIDocument1 : HtmlDocument
    {
        
        public UIBMIDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "BMI";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/BMI/NewPerson";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:15444/BMI/NewPerson";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UISocialSecurityNumberEdit
        {
            get
            {
                if ((this.mUISocialSecurityNumberEdit == null))
                {
                    this.mUISocialSecurityNumberEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUISocialSecurityNumberEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "socialSecurityNumber";
                    this.mUISocialSecurityNumberEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "socialSecurityNumber";
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"socialSecurityNumber\" id=\"socialSe";
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUISocialSecurityNumberEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUISocialSecurityNumberEdit;
            }
        }
        
        public HtmlEdit UIBirthDateEdit
        {
            get
            {
                if ((this.mUIBirthDateEdit == null))
                {
                    this.mUIBirthDateEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIBirthDateEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "birthDate";
                    this.mUIBirthDateEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "birthDate";
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "hasDatepicker";
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"birthDate\" class=\"hasDatepicker\" i";
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIBirthDateEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIBirthDateEdit;
            }
        }
        
        public HtmlComboBox UIGenderComboBox
        {
            get
            {
                if ((this.mUIGenderComboBox == null))
                {
                    this.mUIGenderComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIGenderComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "gender";
                    this.mUIGenderComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "gender";
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "2";
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = null;
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"gender\" id=\"gender\" style=\"width: ";
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUIGenderComboBox.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIGenderComboBox;
            }
        }
        
        public HtmlEdit UILengthEdit
        {
            get
            {
                if ((this.mUILengthEdit == null))
                {
                    this.mUILengthEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILengthEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "length";
                    this.mUILengthEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "length";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"length\" id=\"length\" style=\"width: ";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUILengthEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUILengthEdit;
            }
        }
        
        public HtmlEdit UIWeightEdit
        {
            get
            {
                if ((this.mUIWeightEdit == null))
                {
                    this.mUIWeightEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIWeightEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "weight";
                    this.mUIWeightEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "weight";
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"weight\" id=\"weight\" style=\"width: ";
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIWeightEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIWeightEdit;
            }
        }
        
        public HtmlEdit UIDateEdit
        {
            get
            {
                if ((this.mUIDateEdit == null))
                {
                    this.mUIDateEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDateEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "measurementDate";
                    this.mUIDateEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "date";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "hasDatepicker";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"date\" class=\"hasDatepicker\" id=\"me";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "5";
                    this.mUIDateEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIDateEdit;
            }
        }
        
        public HtmlButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btnSubmit";
                    this.mUIOKButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIOKButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "OK";
                    this.mUIOKButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIOKButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIOKButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUIOKButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"btnSubmit\" style=\"float: left;\" type";
                    this.mUIOKButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUIOKButton.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUISocialSecurityNumberEdit;
        
        private HtmlEdit mUIBirthDateEdit;
        
        private HtmlComboBox mUIGenderComboBox;
        
        private HtmlEdit mUILengthEdit;
        
        private HtmlEdit mUIWeightEdit;
        
        private HtmlEdit mUIDateEdit;
        
        private HtmlButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIBMIDocument2 : HtmlDocument
    {
        
        public UIBMIDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "BMI";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/BMI/Overview";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:15444/BMI/Overview";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlButton UINewButton
        {
            get
            {
                if ((this.mUINewButton == null))
                {
                    this.mUINewButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUINewButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btnNewPerson";
                    this.mUINewButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUINewButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "New";
                    this.mUINewButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUINewButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUINewButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUINewButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"btnNewPerson\"";
                    this.mUINewButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUINewButton.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUINewButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUINewButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIBMIDocument3 : HtmlDocument
    {
        
        public UIBMIDocument3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "BMI";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/BMI/NewPerson";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:15444/BMI/NewPerson?birthDate=01%2F01%2F0001%2000%3A00%3A00&gend" +
                "er=Male&date=01%2F01%2F0001%2000%3A00%3A00&length=0&weight=0&bmi=0&state=New&soc" +
                "ialSecurityNumberVisible=True&birthDateVisible=True&genderVisible=True&bmiVisibl" +
                "e=False";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public UIBodyPane UIBodyPane
        {
            get
            {
                if ((this.mUIBodyPane == null))
                {
                    this.mUIBodyPane = new UIBodyPane(this);
                }
                return this.mUIBodyPane;
            }
        }
        #endregion
        
        #region Fields
        private UIBodyPane mUIBodyPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIBodyPane : HtmlDiv
    {
        
        public UIBodyPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "body";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "New person with social security number 1";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"body\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "3";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UINewpersonwithsocialsPane
        {
            get
            {
                if ((this.mUINewpersonwithsocialsPane == null))
                {
                    this.mUINewpersonwithsocialsPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUINewpersonwithsocialsPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUINewpersonwithsocialsPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUINewpersonwithsocialsPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "New person with social security number 1";
                    this.mUINewpersonwithsocialsPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUINewpersonwithsocialsPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "messageField";
                    this.mUINewpersonwithsocialsPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"messageField\"";
                    this.mUINewpersonwithsocialsPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "5";
                    this.mUINewpersonwithsocialsPane.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUINewpersonwithsocialsPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUINewpersonwithsocialsPane;
        #endregion
    }
}
