// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Specflow_UI_MSCUI.Map.BMIStartMapClasses
{
    using System.CodeDom.Compiler;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;


    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class BMIStartMap
    {
        
        #region Properties
        public UIBMIInternetExplorerWindow UIBMIInternetExplorerWindow
        {
            get
            {
                if ((this.mUIBMIInternetExplorerWindow == null))
                {
                    this.mUIBMIInternetExplorerWindow = new UIBMIInternetExplorerWindow();
                }
                return this.mUIBMIInternetExplorerWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIBMIInternetExplorerWindow mUIBMIInternetExplorerWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBMIInternetExplorerWindow : BrowserWindow
    {
        
        public UIBMIInternetExplorerWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "BMI";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIBMIDocument UIBMIDocument
        {
            get
            {
                if ((this.mUIBMIDocument == null))
                {
                    this.mUIBMIDocument = new UIBMIDocument(this);
                }
                return this.mUIBMIDocument;
            }
        }
        
        public UIBMIDocument1 UIBMIDocument1
        {
            get
            {
                if ((this.mUIBMIDocument1 == null))
                {
                    this.mUIBMIDocument1 = new UIBMIDocument1(this);
                }
                return this.mUIBMIDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIBMIDocument mUIBMIDocument;
        
        private UIBMIDocument1 mUIBMIDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBMIDocument : HtmlDocument
    {
        
        public UIBMIDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "BMI";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:15444/";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlButton UINewButton
        {
            get
            {
                if ((this.mUINewButton == null))
                {
                    this.mUINewButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUINewButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btnNewPerson";
                    this.mUINewButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUINewButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "New";
                    this.mUINewButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUINewButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUINewButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUINewButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"btnNewPerson\"";
                    this.mUINewButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUINewButton.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUINewButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUINewButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBMIDocument1 : HtmlDocument
    {
        
        public UIBMIDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "BMI";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/BMI/Overview";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:15444/BMI/Overview";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public UIItem10NewPane UIItem10NewPane
        {
            get
            {
                if ((this.mUIItem10NewPane == null))
                {
                    this.mUIItem10NewPane = new UIItem10NewPane(this);
                }
                return this.mUIItem10NewPane;
            }
        }
        #endregion
        
        #region Fields
        private UIItem10NewPane mUIItem10NewPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItem10NewPane : HtmlDiv
    {
        
        public UIItem10NewPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "body";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "10 \r\nNew ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"body\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "3";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIItem10Hyperlink
        {
            get
            {
                if ((this.mUIItem10Hyperlink == null))
                {
                    this.mUIItem10Hyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIItem10Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIItem10Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIItem10Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIItem10Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/BMI/ViewDetail";
                    this.mUIItem10Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIItem10Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:15444/BMI/ViewDetail?sosecNr=10";
                    this.mUIItem10Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIItem10Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/BMI/ViewDetail?sosecNr=10\"";
                    this.mUIItem10Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIItem10Hyperlink.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIItem10Hyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIItem10Hyperlink;
        #endregion
    }
}
