// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UI_MSCUI.Maps.MeasurementMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class MeasurementMap
    {
        
        #region Properties
        public UIBMIInternetExplorerWindow UIBMIInternetExplorerWindow
        {
            get
            {
                if ((this.mUIBMIInternetExplorerWindow == null))
                {
                    this.mUIBMIInternetExplorerWindow = new UIBMIInternetExplorerWindow();
                }
                return this.mUIBMIInternetExplorerWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIBMIInternetExplorerWindow mUIBMIInternetExplorerWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBMIInternetExplorerWindow : BrowserWindow
    {
        
        public UIBMIInternetExplorerWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "BMI";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIBMIDocument UIBMIDocument
        {
            get
            {
                if ((this.mUIBMIDocument == null))
                {
                    this.mUIBMIDocument = new UIBMIDocument(this);
                }
                return this.mUIBMIDocument;
            }
        }
        
        public UIBMIDocument1 UIBMIDocument1
        {
            get
            {
                if ((this.mUIBMIDocument1 == null))
                {
                    this.mUIBMIDocument1 = new UIBMIDocument1(this);
                }
                return this.mUIBMIDocument1;
            }
        }
        
        public UIBMIDocument2 UIBMIDocument2
        {
            get
            {
                if ((this.mUIBMIDocument2 == null))
                {
                    this.mUIBMIDocument2 = new UIBMIDocument2(this);
                }
                return this.mUIBMIDocument2;
            }
        }
        
        public UIBMIDocument3 UIBMIDocument3
        {
            get
            {
                if ((this.mUIBMIDocument3 == null))
                {
                    this.mUIBMIDocument3 = new UIBMIDocument3(this);
                }
                return this.mUIBMIDocument3;
            }
        }
        #endregion
        
        #region Fields
        private UIBMIDocument mUIBMIDocument;
        
        private UIBMIDocument1 mUIBMIDocument1;
        
        private UIBMIDocument2 mUIBMIDocument2;
        
        private UIBMIDocument3 mUIBMIDocument3;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBMIDocument : HtmlDocument
    {
        
        public UIBMIDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "BMI";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/BMI/AddMeasurement";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:15444/BMI/AddMeasurement";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UILengthEdit
        {
            get
            {
                if ((this.mUILengthEdit == null))
                {
                    this.mUILengthEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILengthEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "length";
                    this.mUILengthEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "length";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"length\" id=\"length\" style=\"width: ";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUILengthEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUILengthEdit;
            }
        }
        
        public HtmlEdit UIWeightEdit
        {
            get
            {
                if ((this.mUIWeightEdit == null))
                {
                    this.mUIWeightEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIWeightEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "weight";
                    this.mUIWeightEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "weight";
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"weight\" id=\"weight\" style=\"width: ";
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIWeightEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIWeightEdit;
            }
        }
        
        public HtmlEdit UIDateEdit
        {
            get
            {
                if ((this.mUIDateEdit == null))
                {
                    this.mUIDateEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDateEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "measurementDate";
                    this.mUIDateEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "date";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "hasDatepicker";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"date\" class=\"hasDatepicker\" id=\"me";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIDateEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIDateEdit;
            }
        }
        
        public HtmlButton UIAddMeasurementButton
        {
            get
            {
                if ((this.mUIAddMeasurementButton == null))
                {
                    this.mUIAddMeasurementButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIAddMeasurementButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btnAddMeasurement";
                    this.mUIAddMeasurementButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIAddMeasurementButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "AddMeasurement";
                    this.mUIAddMeasurementButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIAddMeasurementButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIAddMeasurementButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUIAddMeasurementButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"btnAddMeasurement\" style=\"float: lef";
                    this.mUIAddMeasurementButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUIAddMeasurementButton.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIAddMeasurementButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUILengthEdit;
        
        private HtmlEdit mUIWeightEdit;
        
        private HtmlEdit mUIDateEdit;
        
        private HtmlButton mUIAddMeasurementButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBMIDocument1 : HtmlDocument
    {
        
        public UIBMIDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "BMI";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/BMI/AddMeasurement";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = @"http://localhost:15444/BMI/AddMeasurement?socialSecurityNumber=123456789&birthDate=01%2F01%2F0001%2000%3A00%3A00&gender=Male&date=01%2F01%2F0001%2000%3A00%3A00&length=0&weight=0&bmi=0&state=Measurement&socialSecurityNumberVisible=False&birthDateVisible=False&genderVisible=False&bmiVisible=False";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIDateEdit
        {
            get
            {
                if ((this.mUIDateEdit == null))
                {
                    this.mUIDateEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDateEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "measurementDate";
                    this.mUIDateEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "date";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "hasDatepicker";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"date\" class=\"hasDatepicker\" id=\"me";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIDateEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIDateEdit;
            }
        }
        
        public UIBodyPane UIBodyPane
        {
            get
            {
                if ((this.mUIBodyPane == null))
                {
                    this.mUIBodyPane = new UIBodyPane(this);
                }
                return this.mUIBodyPane;
            }
        }
        
        public HtmlEdit UILengthEdit
        {
            get
            {
                if ((this.mUILengthEdit == null))
                {
                    this.mUILengthEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILengthEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "length";
                    this.mUILengthEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "length";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"length\" id=\"length\" style=\"width: ";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUILengthEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUILengthEdit;
            }
        }
        
        public HtmlButton UIAddMeasurementButton
        {
            get
            {
                if ((this.mUIAddMeasurementButton == null))
                {
                    this.mUIAddMeasurementButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIAddMeasurementButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btnAddMeasurement";
                    this.mUIAddMeasurementButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIAddMeasurementButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "AddMeasurement";
                    this.mUIAddMeasurementButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIAddMeasurementButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIAddMeasurementButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUIAddMeasurementButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"btnAddMeasurement\" style=\"float: lef";
                    this.mUIAddMeasurementButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUIAddMeasurementButton.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIAddMeasurementButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIDateEdit;
        
        private UIBodyPane mUIBodyPane;
        
        private HtmlEdit mUILengthEdit;
        
        private HtmlButton mUIAddMeasurementButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBodyPane : HtmlDiv
    {
        
        public UIBodyPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "body";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Measurement already exists \r\n\r\n\r\n\r\n\r\n\r\nL";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"body\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "3";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIMeasurementalreadyexPane
        {
            get
            {
                if ((this.mUIMeasurementalreadyexPane == null))
                {
                    this.mUIMeasurementalreadyexPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIMeasurementalreadyexPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIMeasurementalreadyexPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIMeasurementalreadyexPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Measurement already exists ";
                    this.mUIMeasurementalreadyexPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIMeasurementalreadyexPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "messageField";
                    this.mUIMeasurementalreadyexPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"messageField\"";
                    this.mUIMeasurementalreadyexPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "5";
                    this.mUIMeasurementalreadyexPane.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIMeasurementalreadyexPane;
            }
        }
        
        public HtmlDiv UIMeasurementalreadyexPane1
        {
            get
            {
                if ((this.mUIMeasurementalreadyexPane1 == null))
                {
                    this.mUIMeasurementalreadyexPane1 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIMeasurementalreadyexPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIMeasurementalreadyexPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIMeasurementalreadyexPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Measurement already exists \r\n\r\n\r\n\r\n\r\n\r\nL";
                    this.mUIMeasurementalreadyexPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIMeasurementalreadyexPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIMeasurementalreadyexPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = null;
                    this.mUIMeasurementalreadyexPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
                    this.mUIMeasurementalreadyexPane1.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIMeasurementalreadyexPane1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIMeasurementalreadyexPane;
        
        private HtmlDiv mUIMeasurementalreadyexPane1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBMIDocument2 : HtmlDocument
    {
        
        public UIBMIDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "BMI";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/BMI/AddMeasurement";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = @"http://localhost:15444/BMI/AddMeasurement?socialSecurityNumber=123456789&birthDate=01%2F01%2F0001%2000%3A00%3A00&gender=Male&date=07%2F16%2F2015%2000%3A00%3A00&length=180&weight=75000&bmi=0&state=Measurement&socialSecurityNumberVisible=False&birthDateVisible=False&genderVisible=False&bmiVisible=False";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UILengthEdit
        {
            get
            {
                if ((this.mUILengthEdit == null))
                {
                    this.mUILengthEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILengthEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "length";
                    this.mUILengthEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "length";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"length\" id=\"length\" style=\"width: ";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUILengthEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUILengthEdit;
            }
        }
        
        public HtmlButton UIAddMeasurementButton
        {
            get
            {
                if ((this.mUIAddMeasurementButton == null))
                {
                    this.mUIAddMeasurementButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIAddMeasurementButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btnAddMeasurement";
                    this.mUIAddMeasurementButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIAddMeasurementButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "AddMeasurement";
                    this.mUIAddMeasurementButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIAddMeasurementButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIAddMeasurementButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUIAddMeasurementButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"btnAddMeasurement\" style=\"float: lef";
                    this.mUIAddMeasurementButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUIAddMeasurementButton.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIAddMeasurementButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUILengthEdit;
        
        private HtmlButton mUIAddMeasurementButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBMIDocument3 : HtmlDocument
    {
        
        public UIBMIDocument3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "BMI";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/BMI/AddMeasurement";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = @"http://localhost:15444/BMI/AddMeasurement?socialSecurityNumber=123456789&birthDate=01%2F01%2F0001%2000%3A00%3A00&gender=Male&date=07%2F16%2F2015%2000%3A00%3A00&length=0&weight=75000&bmi=0&state=Measurement&socialSecurityNumberVisible=False&birthDateVisible=False&genderVisible=False&bmiVisible=False";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public UIBodyPane1 UIBodyPane
        {
            get
            {
                if ((this.mUIBodyPane == null))
                {
                    this.mUIBodyPane = new UIBodyPane1(this);
                }
                return this.mUIBodyPane;
            }
        }
        
        public HtmlButton UICancelButton
        {
            get
            {
                if ((this.mUICancelButton == null))
                {
                    this.mUICancelButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUICancelButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btnCancel";
                    this.mUICancelButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUICancelButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Cancel";
                    this.mUICancelButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUICancelButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICancelButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUICancelButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"btnCancel\" style=\"float: left;\" type";
                    this.mUICancelButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUICancelButton.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUICancelButton;
            }
        }
        #endregion
        
        #region Fields
        private UIBodyPane1 mUIBodyPane;
        
        private HtmlButton mUICancelButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBodyPane1 : HtmlDiv
    {
        
        public UIBodyPane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "body";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Length is mandatory\r\n\r\nLength\r\nWeight\r\nM";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"body\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "3";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UILengthismandatoryCustom
        {
            get
            {
                if ((this.mUILengthismandatoryCustom == null))
                {
                    this.mUILengthismandatoryCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUILengthismandatoryCustom.SearchProperties["TagName"] = "LI";
                    this.mUILengthismandatoryCustom.SearchProperties["Id"] = null;
                    this.mUILengthismandatoryCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUILengthismandatoryCustom.FilterProperties["Class"] = null;
                    this.mUILengthismandatoryCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUILengthismandatoryCustom.FilterProperties["InnerText"] = "Length is mandatory";
                    this.mUILengthismandatoryCustom.FilterProperties["TagInstance"] = "1";
                    this.mUILengthismandatoryCustom.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUILengthismandatoryCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUILengthismandatoryCustom;
        #endregion
    }
}
