// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Specflow_UI_MSCUI.Map.NewPersonMapClasses
{
    using System.CodeDom.Compiler;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;


    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class NewPersonMap
    {
        
        #region Properties
        public UIBMIInternetExplorerWindow UIBMIInternetExplorerWindow
        {
            get
            {
                if ((this.mUIBMIInternetExplorerWindow == null))
                {
                    this.mUIBMIInternetExplorerWindow = new UIBMIInternetExplorerWindow();
                }
                return this.mUIBMIInternetExplorerWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIBMIInternetExplorerWindow mUIBMIInternetExplorerWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBMIInternetExplorerWindow : BrowserWindow
    {
        
        public UIBMIInternetExplorerWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "BMI";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIBMIDocument UIBMIDocument
        {
            get
            {
                if ((this.mUIBMIDocument == null))
                {
                    this.mUIBMIDocument = new UIBMIDocument(this);
                }
                return this.mUIBMIDocument;
            }
        }
        
        public UIBMIDocument1 UIBMIDocument1
        {
            get
            {
                if ((this.mUIBMIDocument1 == null))
                {
                    this.mUIBMIDocument1 = new UIBMIDocument1(this);
                }
                return this.mUIBMIDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIBMIDocument mUIBMIDocument;
        
        private UIBMIDocument1 mUIBMIDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBMIDocument : HtmlDocument
    {
        
        public UIBMIDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "BMI";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/BMI/NewPerson";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:15444/BMI/NewPerson";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UISocialSecurityNumberEdit
        {
            get
            {
                if ((this.mUISocialSecurityNumberEdit == null))
                {
                    this.mUISocialSecurityNumberEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUISocialSecurityNumberEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "socialSecurityNumber";
                    this.mUISocialSecurityNumberEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "socialSecurityNumber";
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"socialSecurityNumber\" id=\"socialSe";
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUISocialSecurityNumberEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUISocialSecurityNumberEdit;
            }
        }
        
        public HtmlEdit UIBirthDateEdit
        {
            get
            {
                if ((this.mUIBirthDateEdit == null))
                {
                    this.mUIBirthDateEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIBirthDateEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "birthDate";
                    this.mUIBirthDateEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "birthDate";
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "hasDatepicker";
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"birthDate\" class=\"hasDatepicker\" i";
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIBirthDateEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIBirthDateEdit;
            }
        }
        
        public HtmlComboBox UIGenderComboBox
        {
            get
            {
                if ((this.mUIGenderComboBox == null))
                {
                    this.mUIGenderComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIGenderComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "gender";
                    this.mUIGenderComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "gender";
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "2";
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = null;
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"gender\" id=\"gender\" style=\"width: ";
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUIGenderComboBox.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIGenderComboBox;
            }
        }
        
        public HtmlEdit UILengthEdit
        {
            get
            {
                if ((this.mUILengthEdit == null))
                {
                    this.mUILengthEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILengthEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "length";
                    this.mUILengthEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "length";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"length\" id=\"length\" style=\"width: ";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUILengthEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUILengthEdit;
            }
        }
        
        public HtmlEdit UIWeightEdit
        {
            get
            {
                if ((this.mUIWeightEdit == null))
                {
                    this.mUIWeightEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIWeightEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "weight";
                    this.mUIWeightEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "weight";
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"weight\" id=\"weight\" style=\"width: ";
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIWeightEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIWeightEdit;
            }
        }
        
        public HtmlEdit UIDateEdit
        {
            get
            {
                if ((this.mUIDateEdit == null))
                {
                    this.mUIDateEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDateEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "measurementDate";
                    this.mUIDateEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "date";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "hasDatepicker";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"date\" class=\"hasDatepicker\" id=\"me";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "5";
                    this.mUIDateEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIDateEdit;
            }
        }
        
        public HtmlButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btnSubmit";
                    this.mUIOKButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIOKButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "OK";
                    this.mUIOKButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIOKButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIOKButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUIOKButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"btnSubmit\" style=\"float: left;\" type";
                    this.mUIOKButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUIOKButton.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUISocialSecurityNumberEdit;
        
        private HtmlEdit mUIBirthDateEdit;
        
        private HtmlComboBox mUIGenderComboBox;
        
        private HtmlEdit mUILengthEdit;
        
        private HtmlEdit mUIWeightEdit;
        
        private HtmlEdit mUIDateEdit;
        
        private HtmlButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBMIDocument1 : HtmlDocument
    {
        
        public UIBMIDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "BMI";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/BMI/NewPerson";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:15444/BMI/NewPerson?birthDate=01%2F01%2F0001%2000%3A00%3A00&gend" +
                "er=Male&date=01%2F01%2F0001%2000%3A00%3A00&length=0&weight=0&bmi=0&state=New&soc" +
                "ialSecurityNumberVisible=True&birthDateVisible=True&genderVisible=True&bmiVisibl" +
                "e=False";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public UIBodyPane UIBodyPane
        {
            get
            {
                if ((this.mUIBodyPane == null))
                {
                    this.mUIBodyPane = new UIBodyPane(this);
                }
                return this.mUIBodyPane;
            }
        }
        
        public HtmlButton UICancelButton
        {
            get
            {
                if ((this.mUICancelButton == null))
                {
                    this.mUICancelButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUICancelButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btnCancel";
                    this.mUICancelButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUICancelButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Cancel";
                    this.mUICancelButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUICancelButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICancelButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUICancelButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"btnCancel\" style=\"float: left;\" type";
                    this.mUICancelButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUICancelButton.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUICancelButton;
            }
        }
        
        public UIBodyPane1 UIBodyPane1
        {
            get
            {
                if ((this.mUIBodyPane1 == null))
                {
                    this.mUIBodyPane1 = new UIBodyPane1(this);
                }
                return this.mUIBodyPane1;
            }
        }
        #endregion
        
        #region Fields
        private UIBodyPane mUIBodyPane;
        
        private HtmlButton mUICancelButton;
        
        private UIBodyPane1 mUIBodyPane1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBodyPane : HtmlDiv
    {
        
        public UIBodyPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "body";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "New person with social security number 1";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"body\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "3";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UINewpersonwithsocialsPane
        {
            get
            {
                if ((this.mUINewpersonwithsocialsPane == null))
                {
                    this.mUINewpersonwithsocialsPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUINewpersonwithsocialsPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUINewpersonwithsocialsPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUINewpersonwithsocialsPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "New person with social security number";
                    this.mUINewpersonwithsocialsPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUINewpersonwithsocialsPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "messageField";
                    this.mUINewpersonwithsocialsPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"messageField\"";
                    this.mUINewpersonwithsocialsPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "5";
                    this.mUINewpersonwithsocialsPane.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUINewpersonwithsocialsPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUINewpersonwithsocialsPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBodyPane1 : HtmlDiv
    {
        
        public UIBodyPane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "body";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "The value \'5\' is not valid for birthDate";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"body\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "3";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIThevalue5isnotvalidfCustom
        {
            get
            {
                if ((this.mUIThevalue5isnotvalidfCustom == null))
                {
                    this.mUIThevalue5isnotvalidfCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIThevalue5isnotvalidfCustom.SearchProperties["TagName"] = "LI";
                    this.mUIThevalue5isnotvalidfCustom.SearchProperties["Id"] = null;
                    this.mUIThevalue5isnotvalidfCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIThevalue5isnotvalidfCustom.FilterProperties["Class"] = null;
                    this.mUIThevalue5isnotvalidfCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUIThevalue5isnotvalidfCustom.FilterProperties["InnerText"] = "The value \'5\' is not valid for birthDate";
                    this.mUIThevalue5isnotvalidfCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIThevalue5isnotvalidfCustom.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIThevalue5isnotvalidfCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIThevalue5isnotvalidfCustom;
        #endregion
    }
}
