// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Microsoft.VisualStudio.TestTools.UITesting;
using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;

namespace Specflow_UI_MSCUI.Map.Personview
{
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class PersonViewMap
    {
        
        #region Properties
        public UIBMIInternetExplorerWindow UIBMIInternetExplorerWindow
        {
            get
            {
                if ((this.mUIBMIInternetExplorerWindow == null))
                {
                    this.mUIBMIInternetExplorerWindow = new UIBMIInternetExplorerWindow();
                }
                return this.mUIBMIInternetExplorerWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIBMIInternetExplorerWindow mUIBMIInternetExplorerWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBMIInternetExplorerWindow : BrowserWindow
    {
        
        public UIBMIInternetExplorerWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "BMI";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIBMIDocument UIBMIDocument
        {
            get
            {
                if ((this.mUIBMIDocument == null))
                {
                    this.mUIBMIDocument = new UIBMIDocument(this);
                }
                return this.mUIBMIDocument;
            }
        }
        
        public UIBMIDocument1 UIBMIDocument1
        {
            get
            {
                if ((this.mUIBMIDocument1 == null))
                {
                    this.mUIBMIDocument1 = new UIBMIDocument1(this);
                }
                return this.mUIBMIDocument1;
            }
        }
        
        public UIBMIDocument2 UIBMIDocument2
        {
            get
            {
                if ((this.mUIBMIDocument2 == null))
                {
                    this.mUIBMIDocument2 = new UIBMIDocument2(this);
                }
                return this.mUIBMIDocument2;
            }
        }
        #endregion
        
        #region Fields
        private UIBMIDocument mUIBMIDocument;
        
        private UIBMIDocument1 mUIBMIDocument1;
        
        private UIBMIDocument2 mUIBMIDocument2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBMIDocument : HtmlDocument
    {
        
        public UIBMIDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "BMI";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/BMI/ViewDetail";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:15444/BMI/ViewDetail?sosecNr=10";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UISocialSecurityNumberEdit
        {
            get
            {
                if ((this.mUISocialSecurityNumberEdit == null))
                {
                    this.mUISocialSecurityNumberEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUISocialSecurityNumberEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "socialSecurityNumber";
                    this.mUISocialSecurityNumberEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "socialSecurityNumber";
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"socialSecurityNumber\" disabled=\"di";
                    this.mUISocialSecurityNumberEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUISocialSecurityNumberEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUISocialSecurityNumberEdit;
            }
        }
        
        public HtmlEdit UIBirthDateEdit
        {
            get
            {
                if ((this.mUIBirthDateEdit == null))
                {
                    this.mUIBirthDateEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIBirthDateEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "birthDate";
                    this.mUIBirthDateEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "birthDate";
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"birthDate\" disabled=\"disabled\" id=";
                    this.mUIBirthDateEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIBirthDateEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIBirthDateEdit;
            }
        }
        
        public HtmlComboBox UIGenderComboBox
        {
            get
            {
                if ((this.mUIGenderComboBox == null))
                {
                    this.mUIGenderComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIGenderComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "gender";
                    this.mUIGenderComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "gender";
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "2";
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = null;
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"gender\" disabled=\"disabled\" id=\"ge";
                    this.mUIGenderComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUIGenderComboBox.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIGenderComboBox;
            }
        }
        
        public HtmlEdit UILengthEdit
        {
            get
            {
                if ((this.mUILengthEdit == null))
                {
                    this.mUILengthEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILengthEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "length";
                    this.mUILengthEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "length";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"length\" disabled=\"disabled\" id=\"le";
                    this.mUILengthEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUILengthEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUILengthEdit;
            }
        }
        
        public HtmlEdit UIWeightEdit
        {
            get
            {
                if ((this.mUIWeightEdit == null))
                {
                    this.mUIWeightEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIWeightEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "weight";
                    this.mUIWeightEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "weight";
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"weight\" disabled=\"disabled\" id=\"we";
                    this.mUIWeightEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIWeightEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIWeightEdit;
            }
        }
        
        public HtmlEdit UIDateEdit
        {
            get
            {
                if ((this.mUIDateEdit == null))
                {
                    this.mUIDateEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDateEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "measurementDate";
                    this.mUIDateEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "date";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "hasDatepicker";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"date\" disabled=\"disabled\" class=\"h";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "5";
                    this.mUIDateEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIDateEdit;
            }
        }
        
        public HtmlEdit UIBmiEdit
        {
            get
            {
                if ((this.mUIBmiEdit == null))
                {
                    this.mUIBmiEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIBmiEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "bmi";
                    this.mUIBmiEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "bmi";
                    this.mUIBmiEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIBmiEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIBmiEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIBmiEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIBmiEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"bmi\" disabled=\"disabled\" id=\"bmi\" ";
                    this.mUIBmiEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    this.mUIBmiEdit.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIBmiEdit;
            }
        }
        
        public HtmlButton UIAddMeasurementButton
        {
            get
            {
                if ((this.mUIAddMeasurementButton == null))
                {
                    this.mUIAddMeasurementButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIAddMeasurementButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btnAddMeasurement";
                    this.mUIAddMeasurementButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIAddMeasurementButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "AddMeasurement";
                    this.mUIAddMeasurementButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIAddMeasurementButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIAddMeasurementButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUIAddMeasurementButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"btnAddMeasurement\" style=\"float: lef";
                    this.mUIAddMeasurementButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUIAddMeasurementButton.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIAddMeasurementButton;
            }
        }
        
        public HtmlButton UICancelButton
        {
            get
            {
                if ((this.mUICancelButton == null))
                {
                    this.mUICancelButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUICancelButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btnCancel";
                    this.mUICancelButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUICancelButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Cancel";
                    this.mUICancelButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUICancelButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICancelButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUICancelButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"btnCancel\" style=\"float: left;\" type";
                    this.mUICancelButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUICancelButton.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUICancelButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUISocialSecurityNumberEdit;
        
        private HtmlEdit mUIBirthDateEdit;
        
        private HtmlComboBox mUIGenderComboBox;
        
        private HtmlEdit mUILengthEdit;
        
        private HtmlEdit mUIWeightEdit;
        
        private HtmlEdit mUIDateEdit;
        
        private HtmlEdit mUIBmiEdit;
        
        private HtmlButton mUIAddMeasurementButton;
        
        private HtmlButton mUICancelButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBMIDocument1 : HtmlDocument
    {
        
        public UIBMIDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "BMI";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/BMI/AddMeasurement";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:15444/BMI/AddMeasurement";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlButton UICancelButton
        {
            get
            {
                if ((this.mUICancelButton == null))
                {
                    this.mUICancelButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUICancelButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btnCancel";
                    this.mUICancelButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUICancelButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Cancel";
                    this.mUICancelButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUICancelButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICancelButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUICancelButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"btnCancel\" style=\"float: left;\" type";
                    this.mUICancelButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUICancelButton.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUICancelButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUICancelButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBMIDocument2 : HtmlDocument
    {
        
        public UIBMIDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "BMI";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/BMI/Overview";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:15444/BMI/Overview";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public UIItem10NewPane UIItem10NewPane
        {
            get
            {
                if ((this.mUIItem10NewPane == null))
                {
                    this.mUIItem10NewPane = new UIItem10NewPane(this);
                }
                return this.mUIItem10NewPane;
            }
        }
        #endregion
        
        #region Fields
        private UIItem10NewPane mUIItem10NewPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItem10NewPane : HtmlDiv
    {
        
        public UIItem10NewPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "body";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "10 \r\nNew ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"body\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "3";
            this.WindowTitles.Add("BMI");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIItem10Hyperlink
        {
            get
            {
                if ((this.mUIItem10Hyperlink == null))
                {
                    this.mUIItem10Hyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIItem10Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIItem10Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIItem10Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIItem10Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "10";
                    this.mUIItem10Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/BMI/ViewDetail";
                    this.mUIItem10Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIItem10Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:15444/BMI/ViewDetail?sosecNr=10";
                    this.mUIItem10Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIItem10Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/BMI/ViewDetail?sosecNr=10\"";
                    this.mUIItem10Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIItem10Hyperlink.WindowTitles.Add("BMI");
                    #endregion
                }
                return this.mUIItem10Hyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIItem10Hyperlink;
        #endregion
    }
}
